### ISSUE TITLE
[TODO] Next release

### ISSUE THREAD

**Issue by fython** [fython/PackageTracker#48]
- [x] Update Android Gradle Plugin and Gradle to latest version
- [x] Adapt to new Kotlinyan
- [x] Introduce FontProvider API
- [x] Fix known problem and crashes

**Comment by fython** [comment]
Adaptive Icon is still not ready since we hadn't icon origin PSD.
