### ISSUE TITLE
[Feature] Package Tracker 5.0 Roadmap/Progress

### ISSUE THREAD

**Issue by fython** [fython/PackageTracker#68]
## Description

本次更新内容基本为界面重制，包括所有界面，提供更加人性化、更合理的快递跟踪应用体验。

## TO-DOs

- [x] 项目：从 support 库迁移到 androidx 库（ d3886308197a8ac73142ad1079b000362a78b055 ）
- [x] 项目：提高最低支持 SDK 版本到 Android 6.0 (23) （ 15b801b6f2e73576f742af586784de792d58fcf1 ）
- [x] 项目：升级 Kotlin 到 1.3+（ d3886308197a8ac73142ad1079b000362a78b055 ）
- [x] 项目：从 ReactiveX 系列迁移到 Kotlin Coroutines 解决异步问题（ 5eca1a1d1b403d941470010f52cb5d2bddcde255 ）
- [x] 主页：基本界面重设计
- [x] 主页：过滤/搜索功能实现（ 0a42a0e561f155f42d62e2cadc59fa2e424ea86f ）
- [ ] 主页：下拉刷新动画（暂时不更新）
- [x] 主页：新增包裹
- [x] 主页：本地化包裹状态时间（ 0a42a0e561f155f42d62e2cadc59fa2e424ea86f ）
- [x] 主页：列表顶部显示过滤状态（ cf9ebe036058f1f3e38f3b58469ddfe18a3e3763 ）
- [x] 主页：空列表的提示，需针对各种状态，如没有已到达/搜索无结果（ cf9ebe036058f1f3e38f3b58469ddfe18a3e3763 ）
- [ ] ~主页：平板自适应，即多列~（咕了，综合设计成本和平板用户数量，推迟）
- [x] 扫码：界面重设计
- [x] 扫码：从图库选择（ 3c0e42bf809d56d02133980b6e2014fcd700a667 ）
- [ ] 包裹详情：界面重设计（咕了）
- [x] 设定：界面重设计
- [ ] ~通用：流畅的下滑返回~（无论效果做不做好，感觉还是有点违和，放弃了qwq）
- [x] 通用：浮动 Snackbar（ 5f553009dfcf69ca781e7fe2ebb41a75b1acfc4b ）
- [x] 通用：新的 Material 取色板（ 0a42a0e561f155f42d62e2cadc59fa2e424ea86f ）
- [x] 通用：检查夜间主题的可读性
- [x] 通用：移除各自包裹选择图标的功能（ d3829ecfe4bc467f2b299837b2aac49cdaf893c1 ）
- [x] 通用：新增分类功能：每个分类都有它的名称和图案，提供给用户为包裹归类，并允许在搜索中过滤选择。最好默认提供一些分类。（ c64b9642b47e502bd6e4c57428a510200253fb23 ）
- [x] 快捷方式：App Shortcut 的自适应图标更新（ dd6802eb3e3d68c50402e719c8086a6395096cda c16eb64b4388a1dd7823a52391d3763ae6be114b ）
- [x] 语言：受限于时间精力与知识水平，暂时移除 “繁体中文（香港）”（ da1594bb615b89c8536a796acb5a9fcfce5d24a2 ）

**Comment by fython** [comment]
已经作为正式版发布到 Play Store 和酷安市场~
